=== OBOS-dev/obos-strap/recipes.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "git-url": {
      "type": "string"
    },
    "git-commit": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "version": {
      "type": "array",
      "items": [
        {
          "type": "integer"
        },
        {
          "type": "integer"
        },
        {
          "type": "integer"
        }
      ]
    },
    "depends": {
      "type": "array",
      "items": {}
    },
    "build-depends": {
      "type": "array",
      "items": {}
    },
    "patches": {
      "type": "array",
      "items": {}
    },
    "bootstrap-commands": {
      "type": "array",
      "items": {}
    },
    "build-commands": {
      "type": "array",
      "items": {}
    },
    "install-commands": {
      "type": "array",
      "items": {}
    },
    "host-package": {
      "type": "boolean"
    }
  },
  "required": [
    "name",
    "description",
    "version",
    "depends",
    "build-depends",
    "patches",
    "bootstrap-commands",
    "build-commands",
    "install-commands"
  ]
}

=== OBOS-dev/obos-strap/tests/recipes/hello.json
{
    "name": "hello",
    "description": "Print a friendly, customizable greeting.",
    "url": "https://mirror.csclub.uwaterloo.ca/gnu/hello/hello-2.12.2.tar.gz",
    "version": [ 2,12,2 ],
    "depends": [ "bash>=5.3.0" ],
    "build-depends": [],
    "patches": [],
    "bootstrap-commands": [
        [ "${repo_directory}/hello-2.12.2/configure", "--prefix", "${prefix}" ]
    ],
    "build-commands": [
        [ "make", "all" ]
    ],
    "install-commands": [
        [ "make", "install", "DESTDIR=${destdir}" ],
        [ "make", "install", "DESTDIR=${bin_package_prefix}" ]
    ]
}

=== OBOS-dev/obos-strap/tests/recipes/bash.json
{
    "name": "bash",
    "description": "Bourne Again SHell",
    "version": [ 5,3,0 ],
    "url": "https://mirror.csclub.uwaterloo.ca/gnu/bash/bash-5.3.tar.gz",
    "depends": [],
    "build-depends": [],
    "patches": [],
    "bootstrap-commands": [
        [ "${repo_directory}/bash-5.3/configure", "--prefix", "${prefix}" ]
    ],
    "build-commands": [
        [ "make", "all" ]
    ],
    "install-commands": [
        [ "make", "install", "DESTDIR=${destdir}" ],
        [ "make", "install", "DESTDIR=${bin_package_prefix}" ]
    ]
}
